import Image from "next/image";
import Link from "next/link";
import { lang } from "next/root-params";
import Grid from "../Grid";
import FadeIn from "../FadeIn";
import { getDictionary } from "../../[lang]/dictionaries";

// Centered block, not a form: the real form + calendar live on /contacto
// (a GoHighLevel embed). This section is the closing statement and hand-off,
// not the form itself.
export default async function FinalCta() {
  const [t, locale] = await Promise.all([
    getDictionary().then((d) => d.finalCta),
    lang(),
  ]);

  return (
    <section id="contacto" className="relative overflow-hidden py-24 lg:py-32">
      {/* Generated by scripts/artwork.py's "cta" slot: the ASCII mesh is
          masked by the actual Nettyo mark instead of noise, so the texture
          is the logo, not a random cloud. The ramp's low end equals
          --background, so the centered text stays legible without a scrim. */}
      <Image
        src="/media/cta.avif"
        alt=""
        fill
        sizes="100vw"
        className="object-cover"
      />
      <Grid className="relative">
        <FadeIn className="col-span-2 mx-auto max-w-xl text-center sm:col-span-4 lg:col-span-4 lg:col-start-2">
          <p className="font-mono text-xs tracking-wide text-accent-strong uppercase">
            {t.eyebrow}
          </p>
          <h2 className="mt-6 text-3xl font-medium tracking-tight text-foreground sm:text-4xl">
            {t.headline}
          </h2>
          <p className="mx-auto mt-6 max-w-md text-sm leading-relaxed text-foreground-secondary">
            {t.supporting}
          </p>
          <Link
            href={`/${locale}/contacto`}
            className="mt-10 inline-flex h-14 items-center justify-center bg-foreground px-10 font-mono text-xs tracking-wider text-background uppercase transition-opacity hover:opacity-90 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent-strong"
          >
            {t.cta}
          </Link>
          <p className="mt-8 font-mono text-xs tracking-wide text-foreground-secondary uppercase">
            {t.markers.join(" · ")}
          </p>
        </FadeIn>
      </Grid>
    </section>
  );
}
